Helpdesk/Areas/Employee/Controllers/RequestsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ITHelpDesk.Models;
using HelpDesk.DataAccess.Data;
using Microsoft.AspNetCore.Authorization;
using ITHelpDesk.Utility;
using Microsoft.AspNetCore.Identity;
using ITHelpDesk.DataAccess.Repository.IRepository;

namespace ITHelpDesk.Areas.Employee.Controllers
{
    [Area("Employee")]
    [Authorize(Roles = SD.Role_Employee)]

    public class RequestsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> UserManager;
        private readonly IUnitOfWork _unitOfWork;
        public RequestsController(ApplicationDbContext context, UserManager<IdentityUser> userManager, IUnitOfWork unitOfWork)
        {
            UserManager = userManager;
            _context = context;
            _unitOfWork = unitOfWork;
        }

        // GET: Employee/Requests
        public async Task<IActionResult> Index()
        {
            Console.WriteLine(UserManager.GetUserId(User));
            var uNG_HELPDESKContext = _context.Request.Include(r=>r.Tasks).Include(r => r.Address).Include(r => r.Manager)
                .ThenInclude(r => r.User).Include(r => r.Requestmaker).ThenInclude(r => r.User)
                .Include(r => r.Worker).ThenInclude(r => r.User).Where(r => r.Worker.UserId == UserManager.GetUserId(User)).OrderByDescending(r =>r.RequestId);
            ViewData["score"] = _context.Workers.FirstOrDefault(w => w.UserId == UserManager.GetUserId(User)).Score;
            return View(await uNG_HELPDESKContext.ToListAsync());
        }
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var request = await _context.Request
                .Include(r => r.Address)
                .Include(r => r.Manager)
                .Include(r => r.Requestmaker)
                .Include(r => r.Worker)
                .FirstOrDefaultAsync(m => m.RequestId == id);
            if (request == null)
            {
                return NotFound();
            }

            return View(request);
        }

        // GET: Employee/Requests/Create
        public IActionResult Create()
        {
            ViewData["AddressId"] = new SelectList(_context.Address, "AddressId", "AddressId");
            ViewData["ManagerId"] = new SelectList(_context.Managers, "ManagerId", "ManagerId");
            ViewData["RequestmakerId"] = new SelectList(_context.RequestMakers, "RequestmakerId", "RequestmakerId");
            ViewData["WorkerId"] = new SelectList(_context.Workers, "WorkerId", "WorkerId");
            return View();
        }

        // POST: Employee/Requests/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RequestId,RName,RDescription,RStatus,RWeight,RDateTime,RequestmakerId,AddressId,ManagerId,WorkerId")] Request request)
        {
            if (ModelState.IsValid)
            {
                _context.Add(request);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AddressId"] = new SelectList(_context.Address, "AddressId", "AddressId", request.AddressId);
            ViewData["ManagerId"] = new SelectList(_context.Managers, "ManagerId", "ManagerId", request.ManagerId);
            ViewData["RequestmakerId"] = new SelectList(_context.RequestMakers, "RequestmakerId", "RequestmakerId", request.RequestmakerId);
            ViewData["WorkerId"] = new SelectList(_context.Workers, "WorkerId", "WorkerId", request.WorkerId);
            return View(request);
        }

        // GET: Employee/Requests/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var request = await _context.Request.FindAsync(id);
            if (request == null)
            {
                return NotFound();
            }
            ViewData["AddressId"] = new SelectList(_context.Address, "AddressId", "AddressId", request.AddressId);
            ViewData["ManagerId"] = new SelectList(_context.Managers, "ManagerId", "ManagerId", request.ManagerId);
            ViewData["RequestmakerId"] = new SelectList(_context.RequestMakers, "RequestmakerId", "RequestmakerId", request.RequestmakerId);
            ViewData["WorkerId"] = new SelectList(_context.Workers, "WorkerId", "WorkerId", request.WorkerId);
            return View(request);
        }

        // POST: Employee/Requests/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("RequestId, Worker_Comment,Room,review,RName,RDescription,RStatus,RWeight,RDateTime,TaskId,RequestmakerId,AddressId,ManagerId,WorkerId")] Request request)
        {
            if (id != request.RequestId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(request);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RequestExists(request.RequestId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AddressId"] = new SelectList(_context.Address, "AddressId", "AddressId", request.AddressId);
            ViewData["ManagerId"] = new SelectList(_context.Managers, "ManagerId", "ManagerId", request.ManagerId);
            ViewData["RequestmakerId"] = new SelectList(_context.RequestMakers, "RequestmakerId", "RequestmakerId", request.RequestmakerId);
            ViewData["WorkerId"] = new SelectList(_context.Workers, "WorkerId", "WorkerId", request.WorkerId);
            return View(request);
        }

        // GET: Employee/Requests/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var request = await _context.Request
                .Include(r => r.Address)
                .Include(r => r.Manager)
                .Include(r => r.Requestmaker)
                .Include(r => r.Worker)
                .FirstOrDefaultAsync(m => m.RequestId == id);
            if (request == null)
            {
                return NotFound();
            }

            return View(request);
        }

        // POST: Employee/Requests/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var request = await _context.Request.FindAsync(id);
            _context.Request.Remove(request);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RequestExists(int id)
        {
            return _context.Request.Any(e => e.RequestId == id);
        }

        #region API CALLS

        [HttpPost]
        public IActionResult Accept(int id)
        {
            var objFromDb = _unitOfWork.Request.Get(id);
            if (objFromDb == null)
            {
                return Json(new { success = false, message = "Error while accepting" });
            }

            objFromDb.RStatus = "Taken";
            _unitOfWork.Save();
            return Json(new { success = true, message = "Иш сизга юклатилди!" });

        }

        [HttpPost]
        public IActionResult Deny(int id)
        {
            Rejected rejected = new Rejected();

            var objFromDb = _unitOfWork.Request.Get(id);

            rejected.WorkerId = objFromDb.WorkerId;
            rejected.RequestId = objFromDb.RequestId;

            _unitOfWork.Rejected.Add(rejected);

            if (objFromDb == null)
            {
                return Json(new { success = false, message = "Рад етишда хатолик юз берди!" });
            }

            objFromDb.RStatus = "red";
            _unitOfWork.Save();
            return Json(new { success = true, message = "Рад етилди!" });

        }

        #endregion
    }
}

Helpdesk/Areas/Manager/Controllers/WorkersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ITHelpDesk.Models;
using HelpDesk.DataAccess.Data;
using Microsoft.AspNetCore.Authorization;
using ITHelpDesk.Utility;
using Microsoft.AspNetCore.Identity;
using System.Dynamic;

namespace ITHelpDesk.Areas.Admin.Controllers
{
    [Area("Manager")]
    [Authorize(Roles = SD.Role_Manager)]
    public class WorkersController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> UserManager;
        public WorkersController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            UserManager = userManager;
        }

        // GET: Admin/Workers
        public async Task<IActionResult> Index()
        {
            

            var Manager = _context.Managers.ToList().FirstOrDefault(u => u.UserId == UserManager.GetUserId(User)).ManagerId;

            var uNG_HELPDESKContext = _context.Workers.Include(w => w.Manager).Where(w => w.ManagerId == Manager).Include(w => w.User);
            return View(await uNG_HELPDESKContext.ToListAsync());
        
    }

        //Employee Contacts Action
        public IActionResult Contacts()
        {
            dynamic model = new ExpandoObject();
            model.Workers = _context.Workers.Include(r => r.Manager).Include(r => r.Request).Include(r => r.User).ThenInclude(u => u.Address).ToList();
            model.Requests = _context.Request.ToList();
            return View(model);
        }

        // GET: Admin/Workers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var workers = await _context.Workers
                .Include(w => w.Manager)
                .Include(w => w.User)
                .FirstOrDefaultAsync(m => m.WorkerId == id);
            if (workers == null)
            {
                return NotFound();
            }

            return View(workers);
        }

        // GET: Admin/Workers/Create
        public IActionResult Create()
        {
            ViewData["ManagerId"] = new SelectList(_context.Managers, "ManagerId", "ManagerId");
            ViewData["Id"] = new SelectList(_context.Users, "Id", "Id");
            return View();
        }

        // POST: Admin/Workers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("WorkerId,Score,NOfWorks,State,Queue,Id,ManagerId")] Workers workers)
        {
            if (ModelState.IsValid)
            {
                _context.Add(workers);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ManagerId"] = new SelectList(_context.Managers, "ManagerId", "ManagerId", workers.ManagerId);
            ViewData["Id"] = new SelectList(_context.Users, "Id", "Id", workers.UserId);
            return View(workers);
        }

        // GET: Admin/Workers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var workers = await _context.Workers.FindAsync(id);
            if (workers == null)
            {
                return NotFound();
            }
            ViewData["ManagerId"] = new SelectList(_context.Managers, "ManagerId", "ManagerId", workers.ManagerId);
            ViewData["Id"] = new SelectList(_context.Users, "Id", "Id", workers.UserId);
            return View(workers);
        }

        // POST: Admin/Workers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("WorkerId,Score,NOfWorks,State,Queue,Id,ManagerId")] Workers workers)
        {
            if (id != workers.WorkerId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(workers);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!WorkersExists(workers.WorkerId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ManagerId"] = new SelectList(_context.Managers, "ManagerId", "ManagerId", workers.ManagerId);
            ViewData["UserId"] = new SelectList(_context.Users, "UerId", "UserId", workers.UserId);
            return View(workers);
        }

        // GET: Admin/Workers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var workers = await _context.Workers
                .Include(w => w.Manager)
                .Include(w => w.User)
                .FirstOrDefaultAsync(m => m.WorkerId == id);
            if (workers == null)
            {
                return NotFound();
            }

            return View(workers);
        }

        // POST: Admin/Workers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var workers = await _context.Workers.FindAsync(id);
            _context.Workers.Remove(workers);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool WorkersExists(int id)
        {
            return _context.Workers.Any(e => e.WorkerId == id);
        }
    }
}

Helpdesk/Views/Shared/_CreateAndBackToListButton.cshtml
@model ITHelpDesk.Models.Address
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

<div class="row">
    <div class="col">
        <button type="submit" class="mb-2 mr-2 btn btn-primary active form-control">@Localizer["create"]</button>
    </div>
    <div class="col">
        <a asp-action="Index" class="mb-2 mr-2 btn btn-success active form-control">@Localizer["exit"]</a>
    </div>
</div>

Helpdesk/Views/Shared/_DashboardModalPartial.cshtml
@using ITHelpDesk.Utility
@using ITHelpDesk.Models
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

@{
    var request = new Request();

    string id = null;

    bool free = false;

    string number = null;
}

<!-- Large modal -->


@if (User.IsInRole(SD.Role_HeadManager) || User.IsInRole(SD.Role_Manager) && ViewContext.RouteData.Values["action"].ToString().Equals("Dashboard"))
{

    @foreach (var worker in Model.Workers)
    {
        @foreach (var _request in Model.Requests)
        {
            free = false;

            @if (_request.WorkerId == worker.WorkerId && _request.RStatus.Equals("Taken"))
            { request = _request; break; }

            else { free = true; }
        }

        id = string.Concat("Id", worker.WorkerId.ToString());
        <div class="modal fade " tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" id=@id aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content" style="background-color:#00BCD4">
                    @if (!free)
                    {
                        <div class="modal-header" style="background-color:#00BCD4">


                            @{ number = string.Concat("A", request.RequestId.ToString());
                            }
                            <h5 class="modal-title text-light" id="exampleModalLongTitle" style="background-color:darkcyan">&nbsp;@Localizer["request"] № <span>@number</span>&nbsp;</h5>

                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body" style="color:white">
                            <p>@Localizer["rtitle"]: @request.RName</p>
                            <p>@Localizer["description"]: @request.RDescription</p>
                            <p>@Localizer["sender"]: @request.Requestmaker.User.Fullname</p>
                            <p>@Localizer["time"]: @request.RDateTime</p>
                            <p>@Localizer["worker"]: @worker.User.Fullname</p>
                            <p>@Localizer["manager"]: @worker.Manager.User.Fullname</p>
                        </div>
                    }

                    else
                    {
                        <div class="modal-body" style="color:white">
                            <h6>@Localizer["now"] @worker.User.Fullname @Localizer["nothing"]</h6>
                        </div>
                    }






                    <div class="modal-footer" style="background-color:#00BCD4">
                        <button type="button" class="btn" data-dismiss="modal" style="background-color:white">@Localizer["exit"]</button>
                        @*<button type="button" class="btn" style="background-color:white">Save changes</button>*@
                    </div>
                </div>
            </div>
        </div>
    }
}

Helpdesk/Views/Shared/_EditAndBackToListButton.cshtml
@model int
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-primary form-control" asp-route-addressId="@Model">@Localizer["manage"]</button>
    </div>
    <div class="col">
        <a asp-action="Index" class="btn btn-success form-control">@Localizer["exit"]</a>
    </div>
</div>

Helpdesk/Views/Shared/_ModalViewInCalendar.cshtml
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title"><span id="eventTitle"></span></h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <p id="pDetails"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

Helpdesk/Views/Shared/_NotFound.cshtml
@model int
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@{ Layout = null;}

<!doctype html>
<html class="no-js" lang="">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>415 Helpdesk</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- favicon
        ============================================ -->
    <link rel="shortcut icon" type="image/x-icon" href="img/favicon.ico">
    <!-- Google Fonts
        ============================================ -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,700,900" rel="stylesheet">
    <!-- Bootstrap CSS
        ============================================ -->
    <link rel="stylesheet" href="~/register/css/bootstrap.min.css">
    <!-- font awesome CSS
        ============================================ -->
    <link rel="stylesheet" href="~/register/css/font-awesome.min.css">

    <!-- animate CSS
        ============================================ -->
    <link rel="stylesheet" href="~/register/css/animate.css">

    <!-- Notika icon CSS
        ============================================ -->
    <link rel="stylesheet" href="~/register/css/notika-custom-icon.css">
    <!-- main CSS
        ============================================ -->
    <link rel="stylesheet" href="~/register/css/main.css">
    <!-- style CSS
        ============================================ -->
    <link rel="stylesheet" href="~/register/style.css">
    <!-- responsive CSS
        ============================================ -->
    <link rel="stylesheet" href="~/register/css/responsive.css">
    <!-- dropzone JS
        ============================================ -->
    <link rel="stylesheet" href="~/lib/dropzone/dist/dropzone.css">

</head>

<body>
    <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
    <!-- 404 Page area Start-->
    <div class="error-page-area">
        <div class="error-page-wrap">
            <i class="notika-icon notika-close" style="color:#00BCD4"></i>
            <h2>@Localizer["error"] <span class="counter" style="color:#00BCD4">404</span></h2>
            <p>
                @Localizer["sorry"]
            </p>
            <a asp-action="Contacts" class="btn" style="background-color:#00BCD4">@Localizer["exit"]</a>
            @*<a asp-controller="Requests" asp-action="Dashboard" class="btn error-btn-mg" style="background-color:#00BCD4">АСОСИЙ ОЙНА</a>*@
        <button type="button" class="btn " data-toggle="modal" data-target="#myModaltwo" style="background-color:#00BCD4">@Localizer["upload"]</button>
        </div>
    </div>
    <div class="modal fade" id="myModaltwo" role="dialog">
        <div class="modal-dialog modal-sm nk-cyan">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                    <form asp-action="Upload_Config" asp-area="HeadManager" asp-controller="Workers" asp-route-workerId="@Model"
                          method="post" class="dropzone" id="my-awesome-dropzone" enctype="multipart/form-data">
                        <div class="fallback">
                            <input type="file" name="file" />
                        </div>
                    </form>
                </div>
                @*<div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Save changes</button>
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>*@
            </div>
        </div>
    </div>
    <!-- 404 Page area End-->
    <!-- jquery
        ============================================ -->
    <script src="~/register/js/vendor/jquery-1.12.4.min.js"></script>
    <!-- bootstrap JS
        ============================================ -->
    <script src="~/register/js/bootstrap.min.js"></script>
    <!-- wow JS
        ============================================ -->
    <script src="~/register/js/wow.min.js"></script>

    <!-- counterup JS
        ============================================ -->
    <script src="~/register/js/counterup/jquery.counterup.min.js"></script>
    <script src="~/register/js/counterup/waypoints.min.js"></script>
    <script src="~/register/js/counterup/counterup-active.js"></script>

    <!-- dropzone JS
        ============================================ -->
    <script src="~/lib/dropzone/dist/dropzone.js"></script>
    <script src="~/register/js/wow.min.js"></script>
    <!-- main JS
        ============================================ -->
    <script src="~/register/js/main.js"></script>

</body>



</html>




<script>

    // "myAwesomeDropzone" is the camelized version of the HTML element's ID
    Dropzone.options.myAwesomeDropzone = {
        paramName: "file", // The name that will be used to transfer the file
        maxFilesize: 4, // MB
        maxFiles: 1,
        dictDefaultMessage: "@Html.Raw(Localizer["here"].Value.ToString())",

        acceptedFiles: ".doc, .docx, .pdf",
        dictInvalidFileType: "@Html.Raw(Localizer["only"].Value.ToString())"
    }

</script>

Helpdesk/Views/Shared/_SelectLanguagePartial.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options

@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions

@{
    // получаем сервис IRequestCultureFeature
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    // получаем список поддерживаемых культур
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.NativeName })
        .ToList();
}

<form asp-area="Requester" asp-controller="Home" asp-action="SetLanguage"
      asp-route-returnUrl="@Context.Request.Path"
      method="post" class="form-horizontal">
    <div class="btn-toolbar " role="toolbar" aria-label="Toolbar with button groups">
        <div class="btn-group pt-1" role="group" aria-label="First group1">
           
        </div>
        <div class="btn-group " role="group" aria-label="First group">
            <button name="culture" type="submit" value="uz" class="btn btn-light">
                <img src="~/image/uz.png" style="width:35px; height:20px;" />
            </button>
        </div>
        <div class="btn-group" role="group" aria-label="Second group">
            <button name="culture" value="ru" type="submit" class="btn btn-light">
                <img src="~/image/Flag_of_Russia.png" style="width:35px; height:20px;" />
            </button>
        </div>

    </div>

    
</form>

Helpdesk/Views/Shared/_UnsupportedMediaType.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@{ Layout = null;}

<!doctype html>
<html class="no-js" lang="">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>415 Helpdesk</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- favicon
        ============================================ -->
    <link rel="shortcut icon" type="image/x-icon" href="img/favicon.ico">
    <!-- Google Fonts
        ============================================ -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,700,900" rel="stylesheet">
    <!-- Bootstrap CSS
        ============================================ -->
    <link rel="stylesheet" href="~/register/css/bootstrap.min.css">
    <!-- font awesome CSS
        ============================================ -->
    <link rel="stylesheet" href="~/register/css/font-awesome.min.css">

    <!-- animate CSS
        ============================================ -->
    <link rel="stylesheet" href="~/register/css/animate.css">

    <!-- Notika icon CSS
        ============================================ -->
    <link rel="stylesheet" href="~/register/css/notika-custom-icon.css">
    <!-- main CSS
        ============================================ -->
    <link rel="stylesheet" href="~/register/css/main.css">
    <!-- style CSS
        ============================================ -->
    <link rel="stylesheet" href="~/register/style.css">
    <!-- responsive CSS
        ============================================ -->
    <link rel="stylesheet" href="~/register/css/responsive.css">

</head>

<body>
    <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
    <!-- 404 Page area Start-->
    <div class="error-page-area">
        <div class="error-page-wrap">
            <i class="notika-icon notika-close" style="color:#00BCD4"></i>
            <h2>@Localizer["error"] <span class="counter" style="color:#00BCD4">415</span></h2>
            <p>
                @Localizer["sorry"]
            </p>
            <a asp-action="Contacts" class="btn" style="background-color:#00BCD4">@Localizer["exit"]</a>
            <a asp-controller="Requests" asp-action="Dashboard" class="btn error-btn-mg" style="background-color:#00BCD4">@Localizer["main"]</a>
        </div>
    </div>
    <!-- 404 Page area End-->
    <!-- jquery
        ============================================ -->
    <script src="~/register/js/vendor/jquery-1.12.4.min.js"></script>
    <!-- bootstrap JS
        ============================================ -->
    <script src="~/register/js/bootstrap.min.js"></script>
    <!-- wow JS
        ============================================ -->
    <script src="~/register/js/wow.min.js"></script>

    <!-- counterup JS
        ============================================ -->
    <script src="~/register/js/counterup/jquery.counterup.min.js"></script>
    <script src="~/register/js/counterup/waypoints.min.js"></script>
    <script src="~/register/js/counterup/counterup-active.js"></script>

    <!-- main JS
        ============================================ -->
    <script src="~/register/js/main.js"></script>
</body>

</html>