Helpdesk/Areas/Requester/Controllers/RequestSSenderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ITHelpDesk.Models;
using HelpDesk.DataAccess.Data;
using Microsoft.AspNetCore.Identity;
using System.Runtime.CompilerServices;
using Microsoft.AspNetCore.Authorization;
using ITHelpDesk.Utility;
using System.Runtime.InteropServices;

namespace ITHelpDesk.Controllers
{
    [Area("Requester")]
    [Authorize(Roles = SD.Role_Requester)]
    public class RequestSSenderController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly SignInManager<IdentityUser> SignInManager;
        private readonly UserManager<IdentityUser> UserManager;
        
        public RequestSSenderController(ApplicationDbContext context, SignInManager<IdentityUser> signInManager, UserManager<IdentityUser> userManager)
        {
            _context = context;
            SignInManager = signInManager;
            UserManager = userManager;

        }


        // GET: Requests

        public async Task<IActionResult> Index()
        {
            var uNG_HELPDESKContext = _context.Request.Include(t => t.Tasks).Include(r => r.Address).Include(r => r.Manager).ThenInclude(u => u.User).
                           Include(r => r.Requestmaker).Include(r => r.Worker).ThenInclude(u => u.User).Where(r => r.Requestmaker.UserId == UserManager.GetUserId(User)).OrderByDescending(r => r.RequestId)
                           .Select(p => new Request
                           {
                               RequestId = p.RequestId,
                               RName = p.RName,
                               RDescription = p.RDescription,
                               RStatus = p.RStatus,
                               RWeight = p.RWeight,
                               RDateTime = p.RDateTime,
                               review = p.review,
                               Worker_Comment = p.Worker_Comment,
                               JavascriptToRun = p.JavascriptToRun,
                               Room = p.Room,
                               AddressId = p.AddressId,
                    //date = p.date,
                               TaskId = p.TaskId,
                               Tasks = p.Tasks,
                               Address = p.Address,
                               Requestmaker = p.Requestmaker,
                               Manager = p.Manager,
                               Worker = p.Worker,
                               RequestmakerId = p.RequestmakerId,
                               ManagerId = p.ManagerId,
                               WorkerId = p.WorkerId,
                               Completed_at = p.Completed_at,
                               YourOrder = _context.Request.Include(w => w.Worker).ThenInclude(w => w.Request).Where(r => r.WorkerId == p.WorkerId && (DateTime.Compare(p.RDateTime.Date, r.RDateTime.Date) > 0) && (p.RStatus == "yellow" || p.RStatus == "Taken") && r.RStatus == p.RStatus).Count() + 1,
                           });
            return View(await uNG_HELPDESKContext.ToListAsync());
        }

        // GET: Requests/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var request = await _context.Request
                .Include(r => r.Address)
                .Include(r => r.Manager)
                .Include(r => r.Requestmaker)
                .Include(r => r.Worker)
                .FirstOrDefaultAsync(m => m.RequestId == id);
            if (request == null)
            {
                return NotFound();
            }

            return View(request);
        }

        // GET: Requests/Create
        public IActionResult Create()
        {
            var AddressID = _context.User.Include(i => i.Address).ToList().FirstOrDefault(u => u.Id == UserManager.GetUserId(User)).Address.Full;
          //  string a = _context.Address.ToList().FirstOrDefault(i => i.AddressId == AddressID).Full;
            //ViewData["AddressId"] = new SelectList(_context.Address, "AddressId", "Full");
            List<SelectListItem> address = new List<SelectListItem>();
            foreach (var item in _context.Address)
            {
                SelectListItem sel = new SelectListItem
                {
                    Text = item.Full,
                    Value = item.AddressId.ToString(),
                    Selected = item.Full == AddressID,
                };
                SelectListItem s = sel;
                address.Add(s);
            }
            ViewData["AddressId"] = address;

            

            ViewData["ManagerId"] = new SelectList(_context.Managers, "ManagerId", "ManagerId");
            ViewData["RequestmakerId"] = new SelectList(_context.RequestMakers, "RequestmakerId", "RequestmakerId");
            ViewData["WorkerId"] = new SelectList(_context.Workers, "WorkerId", "WorkerId");
            
            return View();
        }

        // POST: Requests/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.     
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RequestId,RName,RDescription,AddressId, Room, ManagerId")] Request request)
        {
            if (ModelState.IsValid)
            {
                var requestMakerList = _context.RequestMakers.ToList();
                // var managerList = _context.Managers.ToList();

                request.RequestmakerId = requestMakerList.FirstOrDefault(u => u.UserId == UserManager.GetUserId(User)).RequestmakerId;
                request.RDateTime = DateTime.Now;
                request.RStatus = "blue";
                _context.Add(request);

                await _context.SaveChangesAsync();


                //request.ManagerId = managerList.FirstOrDefault(u => u.Flag == request.Address.Flag).ManagerId;
                //_context.Add(request);

                //await _context.SaveChangesAsync();
               
                
                
                return RedirectToAction(nameof(Index));
            }

            ViewData["AddressId"] = new SelectList(_context.Address, "AddressId", "AddressId", request.AddressId);
            ViewData["ManagerId"] = new SelectList(_context.Managers, "ManagerId", "ManagerId", request.ManagerId);
            ViewData["RequestmakerId"] = new SelectList(_context.RequestMakers, "RequestmakerId", "RequestmakerId", request.RequestmakerId);
            ViewData["WorkerId"] = new SelectList(_context.Workers, "WorkerId", "WorkerId", request.WorkerId);

           

            return View(request);
        }

        // GET: Requests/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var request = await _context.Request.FindAsync(id);
            if (request == null)
            {
                return NotFound();
            }
            ViewData["AddressId"] = new SelectList(_context.Address, "AddressId", "Full", request.AddressId);
            ViewData["ManagerId"] = new SelectList(_context.Managers, "ManagerId", "ManagerId", request.ManagerId);
            ViewData["RequestmakerId"] = new SelectList(_context.RequestMakers, "RequestmakerId", "RequestmakerId", request.RequestmakerId);
            ViewData["WorkerId"] = new SelectList(_context.Workers, "WorkerId", "WorkerId", request.WorkerId);
            return View(request);
        }

        // POST: Requests/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(bool Done, int id, [Bind("RequestId,Worker_Comment,review,RName,RDescription,Room,RStatus,RWeight,RDateTime,TaskId,RequestmakerId,AddressId,ManagerId,WorkerId")] Request request)
        {
            if (id != request.RequestId)
            {
                return NotFound();
            }


            if (ModelState.IsValid)
            {
                try
                {
                    if (Done == true)
                    {
                        request.RStatus = "green";

                        _context.Update(request);
                        await _context.SaveChangesAsync();
                    }
                    else if (Done == false && request.WorkerId == null)
                    {
                        request.RStatus = "blue";
                        _context.Update(request);
                        await _context.SaveChangesAsync();
                    }
                    else if (Done == false && request.WorkerId != null && request.Worker_Comment == null)
                    {
                        if (request.RStatus == "Taken") {
                            request.RStatus = "Taken";
                        }
                        else 
                        {
                            request.RStatus = "yellow";
                        }
                            
                        _context.Update(request);
                        await _context.SaveChangesAsync();
                    }
                    else if (Done == false && request.WorkerId != null && request.Worker_Comment != null)
                    {
                        
                        request.RStatus = "Taken";
                        _context.Update(request);
                        await _context.SaveChangesAsync();
                    }
                    _context.Update(request);

Helpdesk/Areas/Requester/Views/RequestSSender/Create.cshtml
@model ITHelpDesk.Models.Request
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

    @{
        ViewData["Title"] = "Create";
    }

    <div class="app-page-title">
        <div class="page-title-wrapper">
            <div class="page-title-heading">
                <div class="page-title-icon font-icon-wrapper font-icon-lg">
                    <i class="pe-7s-menu icon-gradient bg-ripe-malin">
                    </i>
                </div>
                <div>
                    <h4 class="" style="color: #00BCD4;">@Localizer["title"]</h4>
                    <div class="page-title-subheading">

                    </div>
                </div>
            </div>
            <div class="page-title-actions">

            </div>
            <div class="page-title-actions">


            </div>
        </div>
    </div>

    <div class="col-lg-5 main-card mb-3 card" style="margin: auto;">
        <div class="form-element-list mg-t-30">
            <form asp-action="Create">
                <div class="cmp-tb-hd">
                    <h2>@Localizer["prompt"]</h2>
                    <p>@Localizer["slow"]!</p>
                </div>
                <div class="row">

                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="col-lg-12 ">
                        <div class="form-group ic-cmp-int float-lb floating-lb">
                            <div class="form-ic-cmp">
                                <i class="notika-icon notika-edit"></i>
                            </div>
                            <div class="nk-int-st">
                                <label style="font-weight:bold">@Localizer["rtitle"]</label>
                                <input type="text" asp-for="RName" class="form-control" placeholder="@Localizer["example"]" required>
                                <span asp-validation-for="RName" class="text-danger"></span>
                            </div>
                            <div class="form-ic-cmp">
                                <i class="notika-icon notika-chat"></i>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-12 ">
                        <div class="form-group ic-cmp-int form-elet-mg">
                            <div class="form-ic-cmp">
                                <i class="notika-icon notika-edit"></i>
                            </div>
                            <div class="nk-int-st">
                                <label style="font-weight:bold">@Localizer["description"]</label>
                                <textarea type="text" class="form-control" asp-for="RDescription" placeholder="" rows="5"></textarea>
                                <span asp-validation-for="RDescription" class="text-danger"></span>
                            </div>
                            <div class="form-ic-cmp">
                                <i class="notika-icon notika-chat"></i>
                            </div>
                        </div>
                    </div>



                    <div class="col-lg-12 " style="padding-top:30px;">
                        <div class="form-group ">
                            <div class="bootstrap-select fm-cmp-mg">

                                <i class="notika-icon notika-house"></i>
                                <label class="control-label" style="font-weight:bold">@Localizer["building"]</label>
                                <select class="selectpicker form-control" asp-for="AddressId" asp-items="ViewBag.AddressId" required></select>

                            </div>
                        </div>
                    </div>



                    <div class="col-lg-12 ">
                        <div class="form-group ic-cmp-int form-elet-mg">
                            <div class="form-ic-cmp">
                                <i class="notika-icon notika-avable"></i>
                            </div>
                            <div class="nk-int-st">
                                <label class="control-label" style="font-weight:bold">@Localizer["room"]?</label>
                                <input type="text" asp-for="Room" class="form-control" placeholder="" required>
                                <span asp-validation-for="Room" class="text-danger"></span>
                            </div>
                            <div class="form-ic-cmp">
                                <i class="notika-icon notika-success"></i>
                            </div>
                        </div>
                    </div>


                    <div style="padding-top: 30px;">


                        <div class="col-lg-12 ">
                            <div class="form-group" style="">
                                <button type="submit" value="Create" class="btn notika-btn-cyan waves-effect text-white">@Localizer["send"]</button>
                            </div>
                        </div>
                    </div>
                </div>



            </form>
            <div>
                <a asp-action="Index" class="text-info">@Localizer["back"]</a>
            </div>
        </div>
    </div>




    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

Helpdesk/Areas/Requester/Views/RequestSSender/Delete.cshtml
@model ITHelpDesk.Models.Request

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Request</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RStatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RStatus)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RWeight)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RWeight)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RDateTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RDateTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address.AddressId)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Manager)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Manager.ManagerId)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Requestmaker)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Requestmaker.RequestmakerId)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Worker)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Worker.WorkerId)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="RequestId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Helpdesk/Areas/Requester/Views/RequestSSender/Details.cshtml
@model ITHelpDesk.Models.Request

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Request</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RStatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RStatus)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RWeight)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RWeight)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RDateTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RDateTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address.AddressId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Manager)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Manager.ManagerId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Requestmaker)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Requestmaker.RequestmakerId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Worker)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Worker.WorkerId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.RequestId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Helpdesk/Areas/Requester/Views/RequestSSender/Index.cshtml
@model IEnumerable<ITHelpDesk.Models.Request>
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

    @{
        ViewData["Title"] = "Index";

        string className = "";
    }


    <div class="app-page-title">
        <div class="page-title-wrapper">
            <div class="page-title-heading">
                <div class="page-title-icon font-icon-wrapper font-icon-lg">
                    <i class="pe-7s-menu icon-gradient bg-ripe-malin">
                    </i>
                </div>
                <div>
                    <h2 class="" style="color: #00BCD4;">@Localizer["title"]</h2>
                    <div class="page-title-subheading">

                    </div>
                </div>
            </div>
            <div class="page-title-actions">

            </div>
            <div class="page-title-actions">


                <a class="btn btn-cyan cyan-icon-notika waves-effect" asp-area="Requester" asp-controller="RequestSSender" asp-action="Create">
                    <i class="notika-icon notika-plus-symbol"></i> @Localizer["send"]
                </a>


            </div>
        </div>
    </div>

    <br />


    <div class="data-table-area">

        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="data-table-list">
                    @*<div class="basic-tb-hd">
                            <h2>Basic Example</h2>
                            <p>It's just that simple. Turn your simple table into a sophisticated data table and offer your users a nice experience and great features without any effort.</p>
                        </div>*@
                    <div class="table-responsive">
                        <table class="align-middle mb-0 table table-borderless table-striped table-hover" id="table" style="border-collapse: separate; border-spacing: 0 3px;">
                            <thead>
                                <tr class="">
                                    <th style="vertical-align:middle">
                                        @Localizer["Rtitle"]
                                    </th>
                                    <th style="vertical-align:middle">
                                        @Localizer["comment"]
                                    </th>

                                    <th style="vertical-align:middle">
                                        @Localizer["work"]
                                    </th>

                                    <th style="vertical-align:middle">
                                        @Localizer["time"]
                                    </th>
                                    <th style="vertical-align:middle">
                                        @Localizer["building"]
                                    </th>
                                    <th style="vertical-align:middle">
                                        @Localizer["room"]
                                    </th>
                                    <th style="vertical-align:middle">
                                        @Localizer["get"]
                                    </th>


                                    <th style="vertical-align:middle">
                                        @Localizer["worker"]
                                    </th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    if (item.RStatus == "Taken")
                                    {
                                        className = "bg-light";

                                    }

                                    else if (item.RStatus == "blue")
                                    {
                                        className = "bg-info";

                                    }
                                    else if (item.RStatus == "yellow")
                                    {
                                        className = "bg-warning";

                                    }
                                    else if (item.RStatus == "red")
                                    {
                                        className = "bg-danger";
                                    }
                                    else if (item.RStatus == "green")
                                    {
                                        className = "bg-success";
                                    }
                                    <tr class=@className>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.RName)
                                        </td>
                                        <td style="display: inline-block;width: 180px;white-space: nowrap;overflow: hidden !important;text-overflow: ellipsis;">
                                            @Html.DisplayFor(modelItem => item.RDescription)
                                        </td>

                                        <td>
                                            @Html.DisplayFor(modelItem => item.Tasks.child)
                                        </td>

                                        <td>
                                            @Html.DisplayFor(modelItem => item.RDateTime)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Address.Full)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Room)
                                        </td>

                                        <td>
                                            @Html.DisplayFor(modelItem => item.Manager.User.Fullname)
                                            @Html.DisplayFor(modelItem => item.Manager.User.PhoneNumber)
                                        </td>

                                        <td>
                                            @Html.DisplayFor(modelItem => item.Worker.User.Fullname)
                                            @Html.DisplayFor(modelItem => item.Worker.User.PhoneNumber)
                                            @if (item.RStatus == "yellow")
                                            {
                                                <br />
                                                <a>Очередь: </a> @Html.DisplayFor(modelItem => item.YourOrder)
                                            }
                                        </td>
                                        <td>

                                            <div class="text-center" style="width:100px">
                                                <a asp-action="Edit" asp-route-id="@item.RequestId" class="btn btn-teal teal-icon-notika waves-effect" style="cursor:pointer">
                                                    <i class="fas fa-edit"></i>
                                                </a>
                                                @*  <a asp-action="Details" asp-route-id="@item.RequestId" class="btn btn-cyan cyan-icon-notika waves-effect" style="cursor:pointer">
                                                                                    <i class="fas fa-info-circle"></i>
                                                                                </a>
                                                                                <a asp-action="Delete" asp-route-id="@item.RequestId" class="btn btn-danger text-white" style="cursor:pointer">
                                                        <i class="fas fa-trash-alt"></i>
                                                    </a>*@
                                            </div>
                                        </td>
                                    </tr>
                                }
                            </tbody>

                            <tfoot>
                                <tr class="">
                                    <th>
                                        @Localizer["Rtitle"]
                                    </th>
                                    <th>
                                        @Localizer["comment"]
                                    </th>

                                    <th>
                                        @Localizer["work"]
                                    </th>

                                    <th>
                                        @Localizer["time"]
                                    </th>
                                    <th>
                                        @Localizer["building"]
                                    </th>
                                    <th>
                                        @Localizer["room"]
                                    </th>
                                    <th>
                                        @Localizer["get"]
                                    </th>


                                    <th>
                                        @Localizer["worker"]
                                    </th>
                                    <th></th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>